services:
  # Configure a standard apache webserver to host our site.
  apache:
    # Use the most recent version of httpd service.
    image: tugboatqa/httpd:latest

    # Run these commands to initialize the server, update it with any libraries and assets required, then build your site.
    commands:
      # Initialize the server.
      init:
        - apt-get update
        - apt-get install -yq ca-certificates curl gnupg
        # Install nvm to manage node versions
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        - nvm install node
        - nvm current
        # Set the webroot for to the Gatsby public folder.
        # Change this if you specify a different root for your public site.
        - ln -snf "${TUGBOAT_ROOT}/public" "${DOCROOT}"

      # Load dependent libraries and assets to prepare the site for build.
      update:
        - nvm use node
        # Run the node.js installer to install Gatsby and its dependencies.
        - npm install

      # Run any commands needed to build the site.
      build:
        # Build the static Gatsby site.
        - npm run build
